from enum import StrEnum


class ChapterStatus(StrEnum):
    PENDING = "PENDING"
    PLANNING = "PLANNING"
    GENERATING = "GENERATING"
    REVIEWING = "REVIEWING"
    DRAFT_READY = "DRAFT_READY"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    EXPORTED = "EXPORTED"
    PUBLISHED_MANUALLY = "PUBLISHED_MANUALLY"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


TERMINAL = {ChapterStatus.PUBLISHED_MANUALLY, ChapterStatus.CANCELLED}
ACTIVE = {ChapterStatus.PENDING, ChapterStatus.PLANNING, ChapterStatus.GENERATING, ChapterStatus.REVIEWING}
